### ISSUE TITLE
nice idea! But no funds on the contract

### ISSUE THREAD

**Issue by amaury1093** [craigmayhew/ethereum-contracts#4]
...which means no incentivization to look for solutions for the 33 problem

**Comment by craigmayhew** [comment]
Hi Amaury,

Thanks for reporting the issue! You are correct, there should have been a small fund on the contract.

I'm happy to let you know that unrelated to this contract, Andrew Booker managed to solve the 33 problem so I don't recommend anyone contribute to this contract.

In the near future I will deploy a new contract for 42, and make sure an initial small fund is there.
